### ISSUE TITLE
Order of operations ignores juxtaposition

### ISSUE THREAD

**Issue by Udelelig** [woheller69/Arity#28]
The use of a PEMDAS order of operations is incomplete, resulting in incorrect answers to algebraic expressions that include multiplication by juxtaposition. E.g. 4÷2(3) should result in a value of 2/3, but instead is resolved to 6. Granted there is no official consensus on the order of operations in theoretical mathematics, however the vast majority of engineers and scientists are more familiar with a PEJMDAS order of operations. Whether this is simply to be corrected or given a configurable setting I leave at your discretion. On a final note, I would like to congratulate you on a truly remarkable application. You do the open source community proud.

**Comment by woheller69** [comment]
This app was originally (until 2010) written by Mihai Preda who also deveoped the Java Arithmetic Engine which is used in this project.

I am not going to change things like that because I do not know the code so well and might break other things.

I discovered the app and mainly updated it to work with current Android versions. So I am trying to keep the app working and do some GUI improvements. But I am really glad people like the app :-)
